-- MySQL Script generated by MySQL Workbench
-- jue 16 abr 2020 19:30:56 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema agregadorLiterario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema agregadorLiterario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `agregadorLiterario` DEFAULT CHARACTER SET utf8 ;
USE `agregadorLiterario` ;

-- -----------------------------------------------------
-- Table `agregadorLiterario`.`CONCURSO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agregadorLiterario`.`CONCURSO` (
  `idConcurso` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `fechaInicio` DATE NULL,
  `fechaFinal` DATE NULL,
  `urlFoto` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  `modalidad` VARCHAR(100) NULL,
  `genero` VARCHAR(100) NULL,
  `GENERO_CONCURSO_idGENERO_CONCURSO` INT NOT NULL,
  PRIMARY KEY (`idConcurso`, `GENERO_CONCURSO_idGENERO_CONCURSO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agregadorLiterario`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agregadorLiterario`.`USUARIO` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(100) NULL,
  `mail` VARCHAR(100) NULL,
  `contraseña` VARCHAR(100) NULL,
  `urlFoto` VARCHAR(100) NULL,
  `descripcion` TEXT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agregadorLiterario`.`INSCRIPCIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agregadorLiterario`.`INSCRIPCIONES` (
  `CONCURSO_idConcurso` INT NOT NULL,
  `USUARIO_idUsuario` INT NOT NULL,
  PRIMARY KEY (`CONCURSO_idConcurso`, `USUARIO_idUsuario`),
  INDEX `fk_CONCURSO_has_USUARIO_USUARIO1_idx` (`USUARIO_idUsuario` ASC),
  INDEX `fk_CONCURSO_has_USUARIO_CONCURSO1_idx` (`CONCURSO_idConcurso` ASC),
  CONSTRAINT `fk_CONCURSO_has_USUARIO_CONCURSO1`
    FOREIGN KEY (`CONCURSO_idConcurso`)
    REFERENCES `agregadorLiterario`.`CONCURSO` (`idConcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONCURSO_has_USUARIO_USUARIO1`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `agregadorLiterario`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `agregadorLiterario`.`VALORACIONES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `agregadorLiterario`.`VALORACIONES` (
  `CONCURSO_idConcurso` INT NOT NULL,
  `USUARIO_idUsuario` INT NOT NULL,
  `puntuacion` INT NULL,
  PRIMARY KEY (`CONCURSO_idConcurso`, `USUARIO_idUsuario`),
  INDEX `fk_CONCURSO_has_USUARIO_USUARIO2_idx` (`USUARIO_idUsuario` ASC),
  INDEX `fk_CONCURSO_has_USUARIO_CONCURSO2_idx` (`CONCURSO_idConcurso` ASC),
  CONSTRAINT `fk_CONCURSO_has_USUARIO_CONCURSO2`
    FOREIGN KEY (`CONCURSO_idConcurso`)
    REFERENCES `agregadorLiterario`.`CONCURSO` (`idConcurso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONCURSO_has_USUARIO_USUARIO2`
    FOREIGN KEY (`USUARIO_idUsuario`)
    REFERENCES `agregadorLiterario`.`USUARIO` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
CONCURSOCONCURSO
